# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160806_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='ser',
            new_name='User',
        ),
    ]
