# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160806_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='Civil',
            new_name='civil',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='User',
            new_name='user',
        ),
    ]
